Develop/cg token
glinda93/cryptogoods pull request #6
Opened 2022-03-22 08:31 UTC by devcrazygit

2022-03-22 11:20 UTC, glinda93 commented on contracts/CryptoGoods.sol
> +            "Purchase would exeed max tokens"
typo

2022-03-22 11:29 UTC, glinda93 requested changes

2022-03-22 11:29 UTC, glinda93 commented on contracts/CryptoGoods.sol
> +            currentPrice * numberOfTokens <= msg.value,
Use `_msgValue()` instead of `msg.value`

2022-03-22 11:29 UTC, glinda93 commented on contracts/CryptoGoods.sol
> +        if (payable(msg.sender).send(balance)) {
I don't think it's a good way to send eth.

https://solidity-by-example.org/sending-ether/

2022-03-22 11:29 UTC, glinda93 commented on contracts/CryptoGoods.sol
> +    function withdraw() public onlyOwner returns (bool) {
Why do we need `withdraw` function in NFT?

2022-03-22 11:29 UTC, glinda93 commented on contracts/CryptoGoods.sol
> +    function setCurrentMarketWithPrice(MarketStatus marketStatus, uint256 price)
Does it have to be renamed to `setCurrentMarketStatusWithPrice` ?

2022-03-22 11:29 UTC, glinda93 commented on contracts/CryptoGoods.sol
> +        _setCurrentMarketWithPrice(marketStatus, price);
Same here

2022-03-22 11:29 UTC, glinda93 commented on contracts/CryptoGoods.sol
> +        if (currentMarketStatus == MarketStatus.PRESALE) {
I don't understand what's happening here.

Can you elaborate?

2022-03-22 11:29 UTC, glinda93 commented on test/index.ts
> +    // it("should be changed into giveaway status", async function() {
Remove zombie codes here

2022-03-22 11:29 UTC, glinda93 commented on test/index.ts
> +import { SignerWithAddress } from "@nomiclabs/hardhat-ethers/signers";
Please use this pattern when writing tests:

```
describe('Class', () => {
   describe('method', () => {
     it('should do something', () => {
        expect(true).toBe(true);
     });
     // optional
     describe('when some condition matches', () => {
       it('should do another thing', () => {
          
       });
     });
   });
});
```

2022-03-23 15:41 UTC, devcrazygit commented on contracts/CryptoGoods.sol
> +        if (currentMarketStatus == MarketStatus.PRESALE) {
Whitelist users can use both of `mintAtPresale` and `mint`.
One for mint in bulk, and another for mint one by one. It depends on the client implementation.

2022-03-23 18:32 UTC, merged